// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx0q7l8q2eXDvzs4XWeih3DfiMLg5FAzE',
    appId: '1:630788660119:web:d8aa4bf7fb3247609ec2d2',
    messagingSenderId: '630788660119',
    projectId: 'supplicationsapp-c3092',
    authDomain: 'supplicationsapp-c3092.firebaseapp.com',
    storageBucket: 'supplicationsapp-c3092.appspot.com',
    measurementId: 'G-DPHSNY0C69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMAyXgLFcVOT7ziKtX5TbD2rYhqHFVOaY',
    appId: '1:630788660119:android:e7b3a049910dd4199ec2d2',
    messagingSenderId: '630788660119',
    projectId: 'supplicationsapp-c3092',
    storageBucket: 'supplicationsapp-c3092.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoUE28UnZZkirvlsEdARTQZkWt3BZKDvU',
    appId: '1:630788660119:ios:59fb9734eb77cfba9ec2d2',
    messagingSenderId: '630788660119',
    projectId: 'supplicationsapp-c3092',
    storageBucket: 'supplicationsapp-c3092.appspot.com',
    iosBundleId: 'com.example.dailySupplicationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoUE28UnZZkirvlsEdARTQZkWt3BZKDvU',
    appId: '1:630788660119:ios:59fb9734eb77cfba9ec2d2',
    messagingSenderId: '630788660119',
    projectId: 'supplicationsapp-c3092',
    storageBucket: 'supplicationsapp-c3092.appspot.com',
    iosBundleId: 'com.example.dailySupplicationsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx0q7l8q2eXDvzs4XWeih3DfiMLg5FAzE',
    appId: '1:630788660119:web:69728fbc08a217819ec2d2',
    messagingSenderId: '630788660119',
    projectId: 'supplicationsapp-c3092',
    authDomain: 'supplicationsapp-c3092.firebaseapp.com',
    storageBucket: 'supplicationsapp-c3092.appspot.com',
    measurementId: 'G-JR7P49BLTK',
  );
}
